	Computer_System u0 (
		.accel_I2C_SDAT             (<connected-to-accel_I2C_SDAT>),             //                accel.I2C_SDAT
		.accel_I2C_SCLK             (<connected-to-accel_I2C_SCLK>),             //                     .I2C_SCLK
		.accel_G_SENSOR_CS_N        (<connected-to-accel_G_SENSOR_CS_N>),        //                     .G_SENSOR_CS_N
		.accel_G_SENSOR_INT         (<connected-to-accel_G_SENSOR_INT>),         //                     .G_SENSOR_INT
		.arduino_gpio_in_port       (<connected-to-arduino_gpio_in_port>),       //         arduino_gpio.in_port
		.arduino_gpio_out_port      (<connected-to-arduino_gpio_out_port>),      //                     .out_port
		.arduino_reset_n_export     (<connected-to-arduino_reset_n_export>),     //      arduino_reset_n.export
		.gpio_a_in_port             (<connected-to-gpio_a_in_port>),             //               gpio_a.in_port
		.gpio_a_out_port            (<connected-to-gpio_a_out_port>),            //                     .out_port
		.gpio_b_in_port             (<connected-to-gpio_b_in_port>),             //               gpio_b.in_port
		.gpio_b_out_port            (<connected-to-gpio_b_out_port>),            //                     .out_port
		.hex3_hex0_export           (<connected-to-hex3_hex0_export>),           //            hex3_hex0.export
		.hex5_hex4_export           (<connected-to-hex5_hex4_export>),           //            hex5_hex4.export
		.leds_export                (<connected-to-leds_export>),                //                 leds.export
		.pushbuttons_export         (<connected-to-pushbuttons_export>),         //          pushbuttons.export
		.master_reset_reset         (<connected-to-master_reset_reset>),         //         master_reset.reset
		.uart0_RXD                  (<connected-to-uart0_RXD>),                  //                uart0.RXD
		.uart0_TXD                  (<connected-to-uart0_TXD>),                  //                     .TXD
		.sdram_ba                   (<connected-to-sdram_ba>),                   //                sdram.ba
		.sdram_addr                 (<connected-to-sdram_addr>),                 //                     .addr
		.sdram_cas_n                (<connected-to-sdram_cas_n>),                //                     .cas_n
		.sdram_cke                  (<connected-to-sdram_cke>),                  //                     .cke
		.sdram_cs_n                 (<connected-to-sdram_cs_n>),                 //                     .cs_n
		.sdram_dq                   (<connected-to-sdram_dq>),                   //                     .dq
		.sdram_dqm                  (<connected-to-sdram_dqm>),                  //                     .dqm
		.sdram_ras_n                (<connected-to-sdram_ras_n>),                //                     .ras_n
		.sdram_we_n                 (<connected-to-sdram_we_n>),                 //                     .we_n
		.sdram_clk_clk              (<connected-to-sdram_clk_clk>),              //            sdram_clk.clk
		.slider_switches_export     (<connected-to-slider_switches_export>),     //      slider_switches.export
		.system_pll_ref_clk_clk     (<connected-to-system_pll_ref_clk_clk>),     //   system_pll_ref_clk.clk
		.system_pll_ref_reset_reset (<connected-to-system_pll_ref_reset_reset>), // system_pll_ref_reset.reset
		.vexriscv_core0_jtag_tms    (<connected-to-vexriscv_core0_jtag_tms>),    //  vexriscv_core0_jtag.tms
		.vexriscv_core0_jtag_tdi    (<connected-to-vexriscv_core0_jtag_tdi>),    //                     .tdi
		.vexriscv_core0_jtag_tdo    (<connected-to-vexriscv_core0_jtag_tdo>),    //                     .tdo
		.vexriscv_core0_jtag_tck    (<connected-to-vexriscv_core0_jtag_tck>),    //                     .tck
		.vga_CLK                    (<connected-to-vga_CLK>),                    //                  vga.CLK
		.vga_HS                     (<connected-to-vga_HS>),                     //                     .HS
		.vga_VS                     (<connected-to-vga_VS>),                     //                     .VS
		.vga_BLANK                  (<connected-to-vga_BLANK>),                  //                     .BLANK
		.vga_SYNC                   (<connected-to-vga_SYNC>),                   //                     .SYNC
		.vga_R                      (<connected-to-vga_R>),                      //                     .R
		.vga_G                      (<connected-to-vga_G>),                      //                     .G
		.vga_B                      (<connected-to-vga_B>),                      //                     .B
		.video_pll_ref_clk_clk      (<connected-to-video_pll_ref_clk_clk>),      //    video_pll_ref_clk.clk
		.video_pll_ref_reset_reset  (<connected-to-video_pll_ref_reset_reset>),  //  video_pll_ref_reset.reset
		.gpio_a_dir_export          (<connected-to-gpio_a_dir_export>),          //           gpio_a_dir.export
		.gpio_b_dir_export          (<connected-to-gpio_b_dir_export>),          //           gpio_b_dir.export
		.gpio_af_mux_a_export       (<connected-to-gpio_af_mux_a_export>),       //        gpio_af_mux_a.export
		.arduino_gpio_dir_export    (<connected-to-arduino_gpio_dir_export>)     //     arduino_gpio_dir.export
	);

